//
//  MusicFactsArray.swift
//  MusicBoxApp
//
//  Created by Sumit Pradhan on 12/11/24.
//

import Foundation

let musicFacts: [String] = [
  "The world's oldest known song is from around 1400 BC.",
  "Beethoven composed music even after going deaf.",
  "The first music video played on MTV was 'Video Killed the Radio Star' by The Buggles.",
  "The Beatles never toured China.",
  "The longest-running #1 song on Billboard was 'Old Town Road' by Lil Nas X.",
  "Mozart composed over 600 pieces of music.",
  "A symphony orchestra has over 100 musicians.",
  "Taylor Swift's first album was released when she was 16.",
  "Adele's '21' album sold over 30 million copies.",
  "The world's most expensive violin was sold for $16 million.",
  "Michael Jackson's 'Thriller' remains the best-selling album ever.",
  "Elvis Presley had 14 number-one albums.",
  "Queen's 'Bohemian Rhapsody' was recorded in one take.",
  "The largest organ in the world has over 33,000 pipes.",
  "The term 'symphony' comes from the Greek word for 'a concord of sounds'.",
  "The world's largest music festival is Summerfest in Milwaukee.",
  "The first recorded sound was made by Thomas Edison in 1877.",
  "The piano has 88 keys.",
  "Beethoven's 'Moonlight Sonata' was composed in 1801.",
  "The longest concert ever lasted 18 hours.",
  "The first Grammy Awards were held in 1959.",
  "Jazz music originated in New Orleans in the early 20th century.",
  "The word 'orchestra' comes from the Greek term for the area in front of the stage.",
  "The shortest song ever is 1.316 seconds long.",
  "The most expensive concert ticket was $1.5 million for a Rolling Stones show.",
  "The first electric guitar was created in 1931.",
  "The first woman inducted into the Rock and Roll Hall of Fame was Aretha Franklin.",
  "The largest choir ever had 121,000 singers.",
  "The Beatles played their final concert in 1966.",
  "The first piano was invented by Bartolomeo Cristofori in 1700.",
  "The first known music notation dates back to ancient Mesopotamia.",
  "'Take Five' by Dave Brubeck is one of the most famous jazz standards.",
  "The first popular video game to feature music was 'Guitar Hero'.",
  "The highest note on a standard piano is C8.",
  "The 'Star-Spangled Banner' was composed by Francis Scott Key in 1814.",
  "Mozart's full name was Johannes Chrysostomus Wolfgangus Theophilus Mozart.",
  "The largest music store in the world is in Tokyo, Japan.",
  "Bob Dylan won the Nobel Prize in Literature in 2016.",
  "A violin has four strings.",
  "The Beatles' song 'Yesterday' is the most covered song of all time.",
  "The first album ever to be released on CD was 'The Visitors' by ABBA.",
  "John Lennon’s famous glasses were round, representing peace and love.",
  "The longest album ever recorded is 'Longplayer', lasting 1,000 years.",
  "The first music streaming service was Rhapsody, launched in 2001.",
  "'Shape of You' by Ed Sheeran is the most-streamed song on Spotify.",
  "The fastest rap in terms of words per second is from 'Godzilla' by Eminem.",
  "The iconic 'Sgt. Pepper's Lonely Hearts Club Band' was released in 1967.",
  "The first music synthesizer was the Theremin, created in 1920.",
  "The best-selling single of all time is 'White Christmas' by Bing Crosby.",
  "The world's first recorded music video was produced in 1957.",
  "Jazz saxophonist John Coltrane was a major influence on modern music.",
  "The longest note held in a song lasted 1 minute and 20 seconds.",
  "Led Zeppelin’s 'Stairway to Heaven' has been covered over 2,000 times.",
  "The first piano concertos were composed by composers like Mozart.",
  "The first woman to win a Grammy for Best New Artist was Billie Holiday.",
  "The Beatles have the most number-one hits on the Billboard Hot 100.",
  "The music genre 'Reggae' originated in Jamaica in the late 1960s.",
  "The first live concert broadcast on TV was by the Rolling Stones in 1969.",
  "The highest-grossing music tour of all time is U2's '360° Tour'.",
  "The song 'Happy Birthday' is in the public domain as of 2016.",
  "The first electric piano was invented in 1940 by Harry Chamberlin.",
  "In 2009, Michael Jackson's 'Thriller' became the first music video to reach 1 billion views on YouTube.",
  "'Bohemian Rhapsody' by Queen has no chorus.",
  "The first recorded use of the term 'rock and roll' was in the 1930s.",
  "The first version of 'Jingle Bells' was written for Thanksgiving, not Christmas.",
  "In 1977, Elvis Presley made his last live performance.",
  "The first known music notation was discovered in Sumer, around 2000 BC.",
  "The first Grammy Award for Album of the Year was awarded to 'The Best of the Soundtrack of the Big Band' in 1959.",
  "The tallest electric guitar ever made is 13 feet tall.",
  "The smallest musical instrument is the Piccolo.",
  "Beethoven's 'Fifth Symphony' opens with one of the most famous motifs in music history.",
  "The most expensive music video ever made was 'Scream' by Michael & Janet Jackson.",
  "The world's most expensive piano is a Crystal Piano worth $3.22 million.",
  "The world's largest record collection has over 6 million records.",
  "The first recordable compact disc was introduced by Sony and Philips in 1982.",
  "'Imagine' by John Lennon is considered one of the most influential songs in history.",
  "The Beatles made their final public performance on a rooftop in 1969.",
  "The world’s largest guitar ensemble consists of 6,000 musicians.",
  "The first recorded use of a synthesizer in music was in the 1960s.",
  "Elvis Presley is often referred to as 'The King of Rock and Roll'.",
  "The first woman to win a Grammy for Record of the Year was Billie Holiday.",
  "The world's largest music library is the British Library Sound Archive.",
  "The first film to feature a soundtrack was 'The Jazz Singer' in 1927.",
  "The first commercial album was 'The Long Playing Record' by Columbia Records in 1948.",
  "The world's first mobile phone ringtone was 'Danny Boy'.",
  "The smallest piano has 25 keys.",
  "The first guitar amplifier was made in 1923.",
  "The first musical note ever recorded was on a cylinder phonograph in 1877.",
  "The most-played song on Spotify is 'Shape of You' by Ed Sheeran.",
  "The shortest song ever recorded is 1.316 seconds long.",
  "The Beatles’ 'Abbey Road' was recorded in just 16 days.",
  "The highest paid musician ever is Michael Jackson.",
  "The first music app was iTunes, released in 2001.",
  "Pink Floyd’s 'The Dark Side of the Moon' stayed on the charts for over 14 years.",
  "The first musical notation system used symbols in ancient Egypt.",
  "The longest music video on YouTube is over 35 hours long.",
  "A harpsichord, an instrument from the 16th century, is similar to a piano but uses plucking instead of hammers.",
  "The world's first opera house opened in Venice, Italy, in 1637.",
  "The piano was originally called the 'gravicembalo col piano e forte'.",
  "The first recorded use of the electric guitar in a song was in 1931.",
  "The largest concert in history was attended by 3.5 million people at Rod Stewart’s concert in 1994.",
  "The world's first sound-on-film technology was demonstrated in 1927.",
  "The first solo performance of the 'Star Wars' theme was done by John Williams.",
  "The oldest surviving complete piece of music is 'The Epitaph of Seikilos', a Greek song from around 200 BC.",
  "The first radio broadcast featuring music occurred in 1920.",
  "The first rock concert held in the Soviet Union was by the Rolling Stones in 1990."
]
